[package]
name = "factory_steel_derive"
version = "0.1.0"
authors = ["Kim Desrosiers <kimdesro@gmail.com>"]

[dependencies]
syn = "0.12.14"
quote = "0.4.2"
proc-macro2 = "0.2"

[lib]
name = "factory_steel_derive"
proc-macro = true

